# Generated by Django 3.1.12 on 2022-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='numberOfBook',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='status',
            field=models.IntegerField(),
        ),
    ]
