# Generated by Django 3.1.12 on 2022-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_auto_20220416_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='status',
            field=models.CharField(max_length=120),
        ),
    ]
