# Generated by Django 3.1.12 on 2022-04-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0003_auto_20220417_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='status',
        ),
    ]
