# Generated by Django 3.1.12 on 2022-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0005_booksmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='sum_books',
            field=models.IntegerField(null=True),
        ),
    ]
