# Generated by Django 3.1.12 on 2022-04-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0006_booksmodel_sum_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='sum_books',
        ),
    ]
