# Generated by Django 3.1.12 on 2022-04-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0008_booksmodel_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='stock',
        ),
    ]
